### ISSUE TITLE
404 error when extracting mentions

### ISSUE THREAD

**Issue by carlosedp** [naholyr/node-twitter-timeline-cleaner#6]
When I try to run it, the following error appears:

```
Extracting Mentions              [                   ] 0%

/usr/local/share/npm/lib/node_modules/twitter-timeline-cleaner/cli/stats.js:86
      if (err) throw err;
                     ^
Error: HTTP Error 404: Not Found
    at /usr/local/share/npm/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/lib/twitter.js:95:14
    at passBackControl (/usr/local/share/npm/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/node_modules/oauth/lib/oauth.js:386:13)
    at IncomingMessage.<anonymous> (/usr/local/share/npm/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/node_modules/oauth/lib/oauth.js:398:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by nbousfield** [comment]
I've run into this error too. I've only had a few minutes to look at it but might have found the problem, if I can fix it tonight I'll submit a fix/fork it.

**Comment by nbousfield** [comment]
I just realized that I am getting a different error, but it probably stems from the same issue. Here is my error:

```
Extracting Direct Messages       [                   ] 0%
/usr/local/lib/node_modules/twitter-timeline-cleaner/cli/stats.js:86
      if (err) throw err;
                     ^
Error: HTTP Error 403: Forbidden
    at /usr/local/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/lib/twitter.js:95:14
    at passBackControl (/usr/local/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/twitter-timeline-cleaner/node_modules/twitter/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
